# coding: utf-8

"""
    Echo

    #### Echos back every URL, method, parameter and header Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will render back everything. 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import greeting
from greeting.rest import ApiException
from greeting.models.member import Member


class TestMember(unittest.TestCase):
    """ Member unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMember(self):
        """
        Test Member
        """
        model = greeting.models.member.Member()


if __name__ == '__main__':
    unittest.main()
