swagger: '2.0'
info:
  version: 1.0.1
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
schemes:
  - http
host: swagger.dev:8080
basePath: /echo
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello:
    get:
      operationId: api.hello.get
      responses:
        200:
          description: Echo GET
    post:
      operationId: api.hello.post
      responses:
        200:
          description: Echo POST
      parameters:
        - name: name
          in: formData
          description: name
          type: string
        - name: year
          in: formData
          description: year
          type: string
  /member/{id}:
    parameters:
      - name: id
        in: path
        description: ID
        type: integer
        required: true
    get:
      operationId: api.member.get
      responses:
        200:
          description: get specified menber object
          schema:
            type: object
            $ref: '#/definitions/Member'

definitions:
  Member:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
